server:
  servlet:
    context-path: /api/v1

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
    elasticsearch:
      host: ${ELK_HOST}
      port: ${ELK_PORT}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      master: ${REDIS_MASTER}
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  main:
    banner-mode: off
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

minio:
  access:
    key: ${S3_ACCESS_KEY_ID}
  secret:
    key: ${S3_SECRET_ACCESS_KEY}
  url:
    public: ${S3_ENDPOINT}
    private: ${S3_ENDPOINT_PRIVATE}

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: 10
  refreshable-duration: 3600

avatar:
  base-url: ${AVATAR_BASE_URL}
